version: "3.2"
services:
  web:
    image: cat-store-django-project:1.0.0 
    restart: always
    command: ["./docker-entrypoint.sh"]
    ports:
      - "8000:8000"
    environment:
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_NAME=cats_db"
      - "DB_USERNAME=admin_user"
      - "DB_PASSWORD=passw0rd"

  db:
    image: postgres:9.6.12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=cats_db

volumes:
  postgres: