# Generated by Django 3.2.4 on 2021-06-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20210618_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='Name',
            new_name='name',
        ),
    ]
